name: yt_bloker_ios
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  audio_session: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Dodajemy to tutaj, żeby system wiedział jak wygenerować ikony
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Ta sekcja MUSI być przy samej lewej krawędzi (zero spacji przed nazwą)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"